import type { Metadata } from 'next';
import { authOptions } from '@/app/api/auth/[...nextauth]/options';
import AppProviders from '@/components/AppProviders';
import { getServerSession } from 'next-auth';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata
    = {
      title: 'Create Next App',
      description: 'Generated by create next app',
    };

async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  // console.log('xxx session RootLayout', session)

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AppProviders session={session}>
          {children}
        </AppProviders>
      </body>
    </html>
  );
}

export default RootLayout;
