name: Build docker image

on:
  push:
    tags: [v*]
    branches: [master, main]
  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}
  DEPLOY_COMMIT_NUMBER: ${{ github.sha }}
  DEPLOY_TAG_VALUE: ${{ github.event.workflow_run.head_branch }}
  BUILD_PLATFORMS: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/s390x

jobs:
  build:
    # Temporarily disabled until switch process in production
    # if: startsWith(github.event.workflow_run.head_branch, 'v')

    runs-on: ubuntu-latest
    # environment: "docker hub"

    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
          submodules: true

      - name: Get Tag or Commit SHA
        id: get_tag
        run: |
          # Attempt to get the tag name for the current commit
          TAG=$(git describe --tags --exact-match 2>/dev/null || echo $GITHUB_SHA)
          echo "DEPLOY_TAG_VALUE=${TAG}" >> $GITHUB_ENV

      # Workaround: https://github.com/docker/build-push-action/issues/461
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ghcr.io
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image of the service
        id: build-and-push-service
        uses: docker/build-push-action@v6
        with:
          context: .
          file: deploy/production/Dockerfile
          platforms: ${{ env.BUILD_PLATFORMS }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.IMAGE_NAME }}:${{ env.DEPLOY_TAG_VALUE }},${{ env.IMAGE_NAME }}:latest
