include:
  - ../../submodules/api/deploy/develop/docker-compose-common.yml

services:
  api:
    image: ghcr.io/sspserver/api:latest
    pull_policy: always
    ports:
      - "18080:8080"
    command: ["--run-migrations"]
    depends_on:
      database:
        condition: service_healthy
      clickhouse-server:
        condition: service_healthy
      clickhouse-init:
        condition: service_started
      redis:
        condition: service_started
      nats:
        condition: service_started
    env_file:
      - ../../submodules/api/deploy/develop/.db.env
      - ../../submodules/api/.env

  control:
    image: node:23
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ../..:/app
    depends_on:
      - api
    entrypoint: /app/deploy/develop/entrypoint.sh
    environment:
      - API_URL=http://api:8080/graphql
      - NEXT_PUBLIC_API_URL=http://localhost:18080/graphql
